spring:
  application:
    name: user-tasks
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/user_tasks?currentSchema=public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
